services:
    training.search_provider.wishlist_search_provider:
        class: Invertus\Training\SearchProvider\WishListSearchProvider
        arguments:
            - '@training.cookies'

    training.provider.context_provider:
        class: Invertus\Training\Provider\ContextProvider

    training.cookies:
        class: Cookie
        factory: [ '@training.provider.context_provider', 'getCookies' ]

