services:
  training.module:
    class: 'training'
    factory: ['Module', 'getInstanceByName']
    arguments:
      - 'training'

  training.get_price:
    class: Invertus\Training\Price\GetProductPrice
    arguments:
      - '@training.module'

  invertus.training.product.search_provider:
    class: Invertus\Training\Product\SearchProvider
    arguments:
      - '@training.module'

