<?php

namespace Invertus\Training\Filter;

use PrestaShop\PrestaShop\Core\Search\Filters;

/**
 * Class ProductFilter proves default filters for our articles grid
 */
final class ArticleFilters extends Filters
{
    /**
     * {@inheritdoc}
     */
    public static function getDefaults()
    {
        return [
            'limit' => 10,
            'offset' => 0,
            'orderBy' => 'id_training_article',
            'sortOrder' => 'desc',
            'filters' => [],
        ];
    }

    public function getFilterId()
    {
        return 'id_training_article'; // TODO: Change the autogenerated stub
    }
}

