training_admin_article:
  path: /
  methods: [GET]
  defaults:
    _controller: 'Invertus\Training\Controller\Admin\TrainingArticleController::listingAction'
    _legacy_controller: AdminTrainingArticle
    _legacy_link: AdminTrainingArticle


training_admin_article_create:
  path: /new
  methods: [GET, POST]
  defaults:
    _controller: 'Invertus\Training\Controller\Admin\TrainingArticleController::createAction'
    _legacy_controller: AdminTrainingArticle
    _legacy_link: AdminTrainingArticle

training_admin_article_edit:
  path: /{articleId}/edit
  methods: [GET, POST]
  defaults:
    _controller: 'Invertus\Training\Controller\Admin\TrainingArticleController::editAction'
    _legacy_controller: AdminTrainingArticle
    _legacy_link: AdminTrainingArticle

training_admin_article_search:
  path: /
  methods: [POST]
  defaults:
    _controller: 'Invertus\Training\Controller\Admin\TrainingArticleController::listingSearchAction'
