services:
  training.module:
    class: 'training'
    factory: ['Module', 'getInstanceByName']
    arguments:
      - 'training'

  training.get_price:
    class: Invertus\Training\Price\GetProductPrice
    arguments:
      - '@training.module'

  training.grid.factory:
    class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
    arguments:
      - '@training.grid.definition.product_grid_definition_factory'
      - '@training.grid.article_data_factory'
      - '@prestashop.core.grid.filter.form_factory'

  training.grid.definition.product_grid_definition_factory:
    class: 'Invertus\Training\Grid\Definition\ArticleGridDefinitionFactory'
    arguments:
      - '@prestashop.core.hook.dispatcher'
      - '@training.module'

  training.grid.article_data_factory:
    class: 'PrestaShop\PrestaShop\Core\Grid\Data\Factory\DoctrineGridDataFactory'
    arguments:
      - '@training.grid.query_builder.article_query_builder'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.core.grid.query.doctrine_query_parser'
      - 'ps_training_article'

  training.grid.query_builder.article_query_builder:
    class: 'Invertus\Training\Grid\QueryBuilder\ArticleQueryBuilder'
    arguments:
      - '@doctrine.dbal.default_connection'
      - '%database_prefix%'
      - "@=service('prestashop.adapter.legacy.context').getContext().language.id"

  training.domain.carrier.query_handler.get_orders_handler:
    class: Invertus\Training\Domain\Carrier\QueryHandler\GetOrdersHandler
    tags:
      - name: tactician.handler
        command: 'Invertus\Training\Domain\Carrier\Query\GetOrdersQuery'


  invertus.ps_training.twig.ps_training_extension:
    class: 'Invertus\Training\Twig\TrainingExtension'
    tags:
      - { name: twig.extension }

  training.update_config_command:
    class: Invertus\Training\Command\UpdateConfigCommand
    tags:
      - { name: console.command }

  training.language.decorating_language_activator:
    class: 'Invertus\Training\Language\DecoratingLanguageActivator'
    arguments:
      - '@training.language.decorating_language_activator.inner'
      - '@prestashop.adapter.legacy.configuration'
    decorates: 'prestashop.adapter.language.activator'
