services:
    training.module:
        class: 'training'
        factory: [ 'Module', 'getInstanceByName' ]
        arguments:
            - 'training'

    training.provider.configuration_options_provider:
        class: Invertus\Training\Provider\ConfigurationOptionsProvider
        arguments:
            - '@training.module'
            - 'name'

    training.grid.factory:
        class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
        arguments:
            - '@training.grid.definition.article_grid_definition_factory'
            - '@training.grid.article_data_factory'
            - '@prestashop.core.grid.filter.form_factory'

    training.grid.definition.article_grid_definition_factory:
        class: 'Invertus\Training\Grid\Definition\ArticleGridDefinitionFactory'
        arguments:
            - '@prestashop.core.hook.dispatcher'
            - '@training.module'

    training.grid.article_data_factory:
        class: 'PrestaShop\PrestaShop\Core\Grid\Data\Factory\DoctrineGridDataFactory'
        arguments:
            - '@training.grid.query_builder.article_query_builder'
            - '@prestashop.core.hook.dispatcher'
            - '@prestashop.core.grid.query.doctrine_query_parser'
            - 'ps_training_article'

    training.grid.query_builder.article_query_builder:
        class: 'Invertus\Training\Grid\QueryBuilder\ArticleQueryBuilder'
        arguments:
            - '@doctrine.dbal.default_connection'
            - '%database_prefix%'
            - "@=service('prestashop.adapter.legacy.context').getContext().language.id"

    training.choice_provider.product_choice_provider:
        class: 'Invertus\Training\Form\ChoiceProvider\ProductChoiceProvider'
        arguments:
            - '@=service("prestashop.adapter.legacy.context").getLanguage().id'

    training.choice_provider.product_choice_provider2:
        class: 'Invertus\Training\Form\ChoiceProvider\ProductChoiceProvider'
        arguments:
            - '@=service("prestashop.adapter.legacy.context").getLanguage().id'

    training.form.data_provider.customer_form_data_provider:
        class: 'Invertus\Training\Form\DataProvider\ArticleDataProvider'

    training.form.article_form_builder:
        class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Builder\FormBuilder'
        factory: 'prestashop.core.form.builder.form_builder_factory:create'
        arguments:
            - 'Invertus\Training\Form\Type\TrainingArticleType'
            - '@training.form.data_provider.customer_form_data_provider'

    Invertus\Training\Form\FormHandler\TrainingArticleFormHandler:
        class: 'Invertus\Training\Form\FormHandler\TrainingArticleFormHandler'

    invertus.training.twig.training_extension:
        class: 'Invertus\Training\Twig\TrainingExtension'
        tags:
            - { name: twig.extension }

    Invertus\Training\API\Cat\Client:
        class: Invertus\Training\API\Cat\Client

    training.form.type.training_article_type:
        class: 'Invertus\Training\Form\Type\TrainingArticleType'
        parent: 'form.type.translatable.aware'
        public: true
        arguments:
            - '@training.choice_provider.product_choice_provider2'
        tags:
            - { name: form.type }

    training.domain.training_article.delete_handler:
        class: 'Invertus\Training\Domain\TrainingArticle\CommandHandler\DeleteTrainingArticleHandler'
        tags:
            - name: tactician.handler
              command: 'Invertus\Training\Domain\TrainingArticle\Command\DeleteTrainingArticle'

    training.data_provider.decorating_performance_data_provider:
        class: 'Invertus\Training\DataProvider\DecoratingPerformanceDataProvider'
        arguments:
            - '@training.data_provider.decorating_performance_data_provider.inner'
        decorates: 'prestashop.adapter.performance.debug_mode.form_provider'

    training.command.set_custom_debug_mode:
        class: 'Invertus\Training\Command\SetCustomDebugMode'
        tags:
            - { name: console.command }
#        parent: 'form.type.translatable.aware'
#
#        public: true
#        tags:
#            - { name: form.type }
